using System.Text;

namespace Asm;

/// <summary>
/// Renders an AsmProgram as a MASM-style listing — a human-readable artifact written next
/// to the linked executable for inspection and debugging.
/// </summary>
public static class ListingWriter
{
    public static string Render(AsmProgram program)
    {
        StringBuilder builder = new();

        builder.AppendLine("; generated by the script compiler asm backend");
        builder.AppendLine();
        builder.AppendLine(".data");
        builder.AppendLine("fmt_int DB \"%lld\", 10, 0");
        builder.AppendLine("fmt_flt DB \"%g\", 10, 0");
        builder.AppendLine();
        builder.AppendLine(".code");
        builder.AppendLine("main PROC");

        foreach (Instruction instruction in program.Text)
        {
            builder.Append("    ");
            builder.AppendLine(Render(instruction));
        }

        builder.AppendLine("main ENDP");
        builder.AppendLine("END");

        return builder.ToString();
    }

    private static string Render(Instruction i) => i.M switch
    {
        Mnemonic.PushReg => $"push {RegName(i.R1)}",
        Mnemonic.PopReg => $"pop {RegName(i.R1)}",
        Mnemonic.MovRegImm64 => $"mov {RegName(i.R1)}, {i.Imm:X}h",
        Mnemonic.MovRegReg => $"mov {RegName(i.R1)}, {RegName(i.R2)}",
        Mnemonic.MovRegMem => $"mov {RegName(i.R1)}, qword ptr {MemName(i.Mem!)}",
        Mnemonic.MovMemReg => $"mov qword ptr {MemName(i.Mem!)}, {RegName(i.R1)}",
        Mnemonic.AddRegReg => $"add {RegName(i.R1)}, {RegName(i.R2)}",
        Mnemonic.SubRegReg => $"sub {RegName(i.R1)}, {RegName(i.R2)}",
        Mnemonic.ImulRegReg => $"imul {RegName(i.R1)}, {RegName(i.R2)}",
        Mnemonic.Cqo => "cqo",
        Mnemonic.IdivReg => $"idiv {RegName(i.R1)}",
        Mnemonic.SubRspImm => $"sub rsp, {i.Imm}",
        Mnemonic.AddRspImm => $"add rsp, {i.Imm}",
        Mnemonic.MovsdXmmMem => $"movsd {XmmName(i.X1)}, qword ptr {MemName(i.Mem!)}",
        Mnemonic.MovsdMemXmm => $"movsd qword ptr {MemName(i.Mem!)}, {XmmName(i.X1)}",
        Mnemonic.AddsdXmmXmm => $"addsd {XmmName(i.X1)}, {XmmName(i.X2)}",
        Mnemonic.SubsdXmmXmm => $"subsd {XmmName(i.X1)}, {XmmName(i.X2)}",
        Mnemonic.MulsdXmmXmm => $"mulsd {XmmName(i.X1)}, {XmmName(i.X2)}",
        Mnemonic.DivsdXmmXmm => $"divsd {XmmName(i.X1)}, {XmmName(i.X2)}",
        Mnemonic.Cvtsi2sdXmmMem => $"cvtsi2sd {XmmName(i.X1)}, qword ptr {MemName(i.Mem!)}",
        Mnemonic.LeaRipRel => $"lea {RegName(i.R1)}, {SymbolName(i.Symbol)}",
        Mnemonic.CallRipIndirect => $"call qword ptr [{SymbolName(i.Symbol)}]",
        Mnemonic.XorReg32Reg32 => $"xor {Reg32Name(i.R1)}, {Reg32Name(i.R2)}",
        Mnemonic.Ret => "ret",
        _ => $"; unknown {i.M}"
    };

    private static string RegName(Reg reg) => reg.ToString().ToLowerInvariant();

    private static string Reg32Name(Reg reg) => reg switch
    {
        Reg.Rax => "eax",
        Reg.Rcx => "ecx",
        Reg.Rdx => "edx",
        Reg.Rbx => "ebx",
        Reg.Rsp => "esp",
        Reg.Rbp => "ebp",
        Reg.Rsi => "esi",
        _ => "edi"
    };

    private static string XmmName(XmmReg reg) => reg.ToString().ToLowerInvariant();

    private static string MemName(MemOperand mem) => mem.Disp switch
    {
        0 => $"[{RegName(mem.Base)}]",
        > 0 => $"[{RegName(mem.Base)}+{mem.Disp}]",
        _ => $"[{RegName(mem.Base)}{mem.Disp}]"
    };

    private static string SymbolName(SymbolRef symbol) => symbol switch
    {
        SymbolRef.FmtInt => "fmt_int",
        SymbolRef.FmtFloat => "fmt_flt",
        SymbolRef.ImpPrintf => "__imp_printf",
        SymbolRef.ImpExitProcess => "__imp_ExitProcess",
        _ => "?"
    };
}
